# Generated by Django 5.0.3 on 2024-04-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_staffuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='core.staffuser'),
        ),
    ]
