# Generated by Django 5.0.3 on 2024-03-30 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.form'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.party'),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('user', 'name')},
        ),
    ]
