# Generated by Django 5.0.4 on 2024-04-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_manage_transactions', 'Can Manage Transactions'), ('can_add_s/p', 'Can Add Sale/Purchase'), ('can_manage_s/p', 'Can Manage Sale/Purchase'))},
        ),
    ]
