# Generated by Django 5.0.4 on 2024-04-21 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_product_alter_transaction_options_transactionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_manage_transactions', 'Can Manage Transactions'), ('can_manage_s/p', 'Can Manage Sale/Purchase'))},
        ),
    ]
