# Generated by Django 5.0.4 on 2024-05-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_trade_bill_number_trade_discount_trade_is_sales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'permissions': (('can_manage_sales', 'Can Manage Sales'), ('can_manage_purchase', 'Can Manage Purchase'))},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_manage_transactions', 'Can Manage Transactions'),)},
        ),
    ]
