# Generated by Django 5.0.4 on 2024-06-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_trade_options_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction'),
        ),
    ]
