# Generated by Django 5.0.4 on 2024-06-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_trade_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='is_sales',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_sales',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
