# Generated by Django 5.0.4 on 2024-06-04 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_transaction_is_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_items', to='accounts.transaction'),
        ),
    ]
