# Generated by Django 5.0.4 on 2024-06-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_trade_transaction_alter_tradeitem_trade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_manage_transactions', 'Can Manage Transactions'), ('can_manage_sales', 'Can Manage Sales'), ('can_manage_purchase', 'Can Manage Purchase'))},
        ),
        migrations.AddField(
            model_name='party',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
