# Generated by Django 5.0.4 on 2024-06-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_party_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
