# Generated by Django 5.0.4 on 2024-06-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_tradeitem_delete_flag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
