# Generated by Django 5.0.4 on 2024-06-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_delete_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charges',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
